name: Install Smoketest

on:
  push:
    paths:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    name: Test Windows installation
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME\venv
        name: Create venv
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pip install git+https://github.com/angr/archinfo.git
        name: Install dependencies
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pip install .
        name: Install pyvex
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          python -c "import pyvex; print('It works!')"
        name: Import pyvex
        shell: cmd

  macos:
    name: Test macOS installation
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          source $HOME/venv/bin/activate
          pip install git+https://github.com/angr/archinfo.git
        name: Install dependencies
      - run: |
          source $HOME/venv/bin/activate
          pip install .
        name: Install pyvex
      - run: |
          source $HOME/venv/bin/activate
          python -c "import pyvex; print('It works!')"
        name: Import pyvex
